## Sequential Model

In [73]:
import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense,Activation
from keras.utils.np_utils import to_categorical

In [74]:
#create the Squential Model
model=Sequential()

In [75]:
# X has shape (num_rows, num_cols), where the training data are stored
# as row vectors
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y = np.array([[0], [1], [1], [0]], dtype=np.float32)
y_binary = to_categorical(y)

In [76]:
X

array([[ 0.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  1.]], dtype=float32)

In [77]:
y_binary

array([[ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.]])

In [78]:
# 1st Layer - Add an input layer of 32 nodes with the same input shape as
# the training samples in X
model.add(Dense(32,input_dim=X.shape[1]))
# Add a softmax activation layer
model.add(Activation('softmax'))
# 2nd layer - Add a fully connected output layer
model.add(Dense(2))
# Add a softmax activation layer
model.add(Activation('softmax'))

In [79]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [80]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_13 (Dense)             (None, 32)                96        
_________________________________________________________________
activation_7 (Activation)    (None, 32)                0         
_________________________________________________________________
dense_14 (Dense)             (None, 2)                 66        
_________________________________________________________________
activation_8 (Activation)    (None, 2)                 0         
Total params: 162
Trainable params: 162
Non-trainable params: 0
_________________________________________________________________


In [81]:
model.fit(X,y_binary,epochs=1000,verbose=0)

In [82]:
model.evaluate(X,y_binary)

4/4 [==============================] - 0s


[0.17056092619895935, 1.0]

In [83]:
model.predict_proba(X)

4/4 [==============================] - 0s


array([[ 0.8163625 ,  0.18363751],
       [ 0.15330724,  0.84669268],
       [ 0.15968157,  0.84031844],
       [ 0.87026697,  0.12973295]], dtype=float32)